version: '3'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: hapi-template
    command: 'bash tools/test.sh'
    working_dir: /app/user
    volumes:
        - '.:/app/user'
    links:
      - postgres

  postgres:
    image: postgres:10.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - '127.0.0.1:7432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
